### ISSUE TITLE
Hey I have refered ur project and I tested it on  a phishing website which I got from phish tank It was shown as safe.The website is this: https://richafoodz45.ml/AT&T/     

### ISSUE THREAD

**Issue by rutunaik** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rohitnaik246** [comment]
Hello, thanks for reaching out. 
When you want to ask any questions/want to post a bug report, you need to fill out the template you posted above with details relevant to your issue and not just post the default template in the issue. Once you have done that, you can then briefly describe the issue in the title. Please post your issue in the following format for me to get a better idea of the issue and the environment in which the issue occurred.

**Comment by rohitnaik246** [comment]
As for an answer to the issue goes, please refer to [this issue](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/issues/5) where I have discussed it.
Thanks!

Closing the issue as the solution is clear. If anything is unclear, please feel free to reopen the issue.
