### ISSUE TITLE
how to set the LOCAL HOST PATH And Client server.php python path on linux

### ISSUE THREAD

**Issue by Chaitrali26** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#11]
Hi rohit,

Could you give more details on how to set the LOCAL HOST PATH And Client server.php python path on linux?

**Comment by JyothsnaVarrier** [comment]
I had this same issue. 
`xhr.open("POST","http://localhost/clientServer.php",false);`
url must be a file on server. For that, in linux, Drop the file in `/var/www/`. 
It worked for me.

**Comment by Chaitrali26** [comment]
Hello Jyothsna,

I am new to all of this. Can you explain a little bit more or provide resources ?

**Comment by rohitnaik246** [comment]
Hi Chaitrali,
This [article about local servers](https://www.dwuser.com/education/content/why-you-need-a-testing-server-and-how-to-do-it/) will help you understand all about local servers.
Further, [this article](https://www.maketecheasier.com/setup-local-web-server-all-platforms/) will help you set up local server for your OS.

Closing this issue for now. Please reopen if you feel you still need help.
