### ISSUE TITLE
Error in Extensions in Google Chrome

### ISSUE THREAD

**Issue by Jigar6591** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#12]

**Comment by Jigar6591** [comment]
I am executing this project on Windows platform and executed the steps as mentioned on your main page. but while testing the phishing attack on any new website, I am seeing this below error:

Error handling response: Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost/Malicious-Web-Content-Detection-Using-Machine-Learning/clientServer.php'.
Context
popup.html
Stack Trace
popup.js:13 (anonymous function)

**Comment by rohitnaik246** [comment]
Can you please fill up the Bug report template so that I get more details about the problem?

**Comment by Jigar6591** [comment]
Hello Mr. Naik,
I am attaching the screenshot of the error. I followed the steps mentioned on your GITHUB README.md file, currently, I am working on Windows platform with python 2.7 and all the latest dependencies are as per your requirement. When I went into detail for the errors in the extension, I found the error as mentioned in the Capture1 int he attachments.


Thanking you.With regards,Jigar Makwana 

    On Sunday, 28 April, 2019, 10:24:11 pm GMT-7, Rohit Naik <notifications@github.com> wrote:  
 
 
Can you please fill up the Bug report template so that I get more details about the problem?

**Comment by rohitnaik246** [comment]
Hi Jigar, I cannot see any screenshot attached here.

**Comment by Jigar6591** [comment]
Hello Rohit,

I am attaching the errors again for your reference:

Thanking you.
With regards,Jigar Makwana 

    On Wednesday, 1 May, 2019, 11:14:13 pm GMT-7, Rohit Naik <notifications@github.com> wrote:  
 
 
Hi Jigar, I cannot see any screenshot attached here.

**Comment by rohitnaik246** [comment]
Hi please check if you can see the screenshot yourself in this issue.
For your reference, this is how you attach images to issues - https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by Jigar6591** [comment]
![Capture](https://user-images.githubusercontent.com/46396404/57199413-78126f00-6f33-11e9-8438-69d4421be93a.JPG)
![Capture1](https://user-images.githubusercontent.com/46396404/57199415-78126f00-6f33-11e9-8673-aa9b3f23d28e.JPG)

**Comment by rohitnaik246** [comment]
Hi Jigar,
I just tested the most updated version of the code by following the steps from the README and I am unable to recreate this error. Please do a git pull and test again.

If still there is an error, I would suggest taking a look at [this link](https://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr).

If you still need help, please fill up the following bug report template so that I can recreate this issue and take it from there -
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

Closing the issue for now as I am not able to see any issue with the updated code.

**Comment by bhavya998** [comment]
@Jigar6591  i am also facing the same issue did u find the solution to it ? if yes please help me out ! thankou @Jigar6591  and @philomathic-guy
