### ISSUE TITLE
error with train.py file

### ISSUE THREAD

**Issue by dR2410** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#13]
![Screenshot (84)](https://user-images.githubusercontent.com/32610235/56868051-f4c0bd00-6a0a-11e9-8076-6cb8cd8d727f.png)
i can't resolve this error help me with it and i am using python 2.7 only

**Comment by rohitnaik246** [comment]
Can you please fill up the Bug report template, so I get more details about the issue?
From my initial assessments, it looks like there is a mismatch with the number of indices in the feature array.

**Comment by dR2410** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/32610235/56880156-4bfd7680-6a79-11e9-9af8-8067b949476f.png)
there is a errror at features line it should take 2D but its taking only 1D i dont know how to resolve that issue

**Comment by rohitnaik246** [comment]
Hi,
I meant this bug report template which you get when you try to file an issue -

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

By completing this report, you will be able to think through the problem (in order to describe it here) and it might help you yourself to solve the issue.

**Comment by shivalekshmi** [comment]
Hi,
I find an error while running this code. Can you please help me with this?
Error 1:

 File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/train.py", line 18, in <module>
    features = data1[:, :-1]
IndexError: too many indices for array

Error 2:
 File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/test.py", line 34, in <module>
    main()
  File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/test.py", line 8, in main
    url = sys.argv[1]
IndexError: list index out of range

**Comment by rohitnaik246** [comment]
Hi Shivalekshmi,
For error 1, make sure you are using python2 to run the file.
For error 2, if you are not passing a command line argument, there will be an error. Read more about sys.argv and how it works. Basically, when you are running the file, you need to pass a URL as a parameter.
I will add code to this to make it more obvious to new users.

Closing this issue for now. Reopen if needed.

**Comment by Shraddha1812** [comment]
> Hi,
> I find an error while running this code. Can you please help me with this?
> Error 1:
> 
> File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/train.py", line 18, in
> features = data1[:, :-1]
> IndexError: too many indices for array
> 
> Error 2:
> File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/test.py", line 34, in
> main()
> File "F:/Malicious-Web-Content-Detection-Using-Machine-Learning-master/test.py", line 8, in main
> url = sys.argv[1]
> IndexError: list index out of range

I'm also facing the same error 1
IndexError: too many indices for array
And yes, I'm using python 2.7.16.
Help me resolve this
