### ISSUE TITLE
ValueError: invalid \x escape

### ISSUE THREAD

**Issue by moneydream07** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#3]
I was trying to implement your project but I got an error in feature_extraction.py as ValueError: invalid \x escape.I searched a lot but wasn't really able to identify issue.

**Comment by rohitnaik246** [comment]
Hi,
Can you please elaborate more on the issue? Probably share some screenshots of it. It would be really helpful to figure out what's going wrong.
Thanks!

**Comment by moneydream07** [comment]
![screenshot 45](https://user-images.githubusercontent.com/20323652/53322808-7d838580-3902-11e9-84f6-df27354949ae.png)
this is the error while running feature_extraction.py probably some issue is in the string.

**Comment by rohitnaik246** [comment]
Hi,
Can you please check a couple of things?
1. Type ```python -V``` and let me know what version you are running. If you are running python3, it might be possible because python2 and python3 handle strings quite differently.
2. If you are using python2, please do a ```git pull``` once, because I just tried running the most updated version of the repo and it seems to be working just fine on my end.

**Comment by moneydream07** [comment]
I am using python 2.7 and did git pull twice.can you tell me what os you are using?

**Comment by rohitnaik246** [comment]
I am using Mac OS. I thought about it but I am not sure how would OS be a problem when what we are running is python.

**Comment by moneydream07** [comment]
Yes you are right but don't know why I am getting this error.can you tell me exact python version you are using like 2.7.1

**Comment by rohitnaik246** [comment]
2.7.13

**Comment by moneydream07** [comment]
Ok so there is no issue with python.

**Comment by moneydream07** [comment]
I think there is some issue in the string where you have mentioned hexadecimal ipv4.

**Comment by moneydream07** [comment]
@rohitnaik246  above error has been solved.now I am getting a new error as operable program or batch file as you can see in the screenshot,hope you can help me in this problem.
![screenshot 48](https://user-images.githubusercontent.com/20323652/53560145-bd9c6f80-3b71-11e9-93a8-b9d7752e633a.png)

**Comment by rohitnaik246** [comment]
1. What was the actual issue for 'ValueError: invalid \x escape'?
2. For debugging, we need to see the full error message. For that, please uncomment line number 14 of ```popup.js``` which is ```alert(xhr.responseText);``` and we can take it ahead from there. I am guessing this is some system specific error.

Thanks

**Comment by moneydream07** [comment]
As this particular problem has been solved I am closing this issue.

**Comment by moneydream07** [comment]
As this particular error has been solved I am closing this issue.

**Comment by nkap11** [comment]
Sir, I was trying to implement your project but I got an error as "operable program or batch file" ,you can see in the screenshot. So @rohitnaik246 sir and @moneydream07 sir please help me to solve this error.
Thanks,

![screenshot](https://user-images.githubusercontent.com/49228708/55470199-caa2f780-5624-11e9-8cc6-1c91c8d1fc6d.jpg)

**Comment by moneydream07** [comment]
> Sir, I was trying to implement your project but I got an error as "operable program or batch file" ,you can see in the screenshot. So @rohitnaik246 sir and @moneydream07 sir please help me to solve this error.
> Thanks,
> 
> ![screenshot](https://user-images.githubusercontent.com/49228708/55470199-caa2f780-5624-11e9-8cc6-1c91c8d1fc6d.jpg)

this error is generated because of the wrong path of either python or php file.

**Comment by nkap11** [comment]
Thanks sir,But now i get an output as "[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished" as shown in Fig.1. Which is the first line of output of test.py file as per Fig.2. So @rohitnaik246  sir and @moneydream07  sir please help me to solve this problem.
Fig.1-
![ss](https://user-images.githubusercontent.com/49228708/55548264-b62c3100-56f0-11e9-8a37-d1ce52c0f01d.jpg)
Fig2.-
![ss1](https://user-images.githubusercontent.com/49228708/55548265-b62c3100-56f0-11e9-94b8-3402a719c652.JPG)
Thanks,
