### ISSUE TITLE
Python version error

### ISSUE THREAD

**Issue by BadduCoder** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#4]
Your project is developed in python2.x, changing it to python3.x is generating multiple errors.
I guess it should be mentioned in readme that this project was developed using python2.x .

**Comment by rohitnaik246** [comment]
Hi,
Yes you are right. It isn't directly mentioned in the README, but there are mentions of it in certain parts of the README. Nevertheless, I have mentioned it explicitly in the README now.
Thanks for pointing that out.
Also, I am planning on changing the project to Python 3.x soon when I get some free time.
