### ISSUE TITLE
Showing every website safe 

### ISSUE THREAD

**Issue by moneydream07** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#5]
I implemented this project with some malicious urls and still it is showing safe.

**Comment by rohitnaik246** [comment]
In that case, you need to train your model better and create your own pkl file. We had trained the model 4 years ago which might get outdated with new data. Feel free to try and work with different models to find which one works best based on the different parameters - Accuracy, Precision, Recall, etc.

Thanks!
