### ISSUE TITLE
how to set the localhost path in featute_extraction.py file in windows 10?

### ISSUE THREAD

**Issue by chaithrakulal** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#6]

**Comment by rohitnaik246** [comment]
If you have xampp installed, your localhost path should be - C:\xampp\htdocs. If you don't you would have to install it, as there is no default local server for Windows.
Closing the issue. Please reopen if you have any other doubts.

**Comment by Chaitrali26** [comment]
How do i set locahost_path in feature_extraction.py file in Ubuntu
