### ISSUE TITLE
Getting error in popup.js

### ISSUE THREAD

**Issue by melek2** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#8]
I'm referring your project, I added your extension in google chrome and when i want too verify if the link is a safe site or not 
i get this error 
![issue](https://user-images.githubusercontent.com/47900774/55514195-62253c00-565f-11e9-8cd2-2cfa1882e459.png)
![Capture du 2019-04-03 22-27-40](https://user-images.githubusercontent.com/47900774/55514335-baf4d480-565f-11e9-9a50-ab0d30479506.png)
I'm using Python 2.7 and Ubuntu.  How to resolve it?

**Comment by rohitnaik246** [comment]
Can you send the error in detail? I cannot quite deduce what the error is from your screenshot.

**Comment by melek2** [comment]
when i want the extension to deduce if the link is safe or not it showing me this 
![issue11](https://user-images.githubusercontent.com/47900774/55550513-427a2c00-56d0-11e9-80c1-2df242183869.png)
![issue22](https://user-images.githubusercontent.com/47900774/55550520-44dc8600-56d0-11e9-915d-46c82dacfe68.png)
and in Extensions, it shows me this error  :
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
error caused of this line : 
xhr.open("POST","http://localhost/Malicious-Web-Content-Detection-Using-Machine-Learning-master/clientServer.php",false);

I hope that shows you clearly my issue

**Comment by melek2** [comment]
i solved my first issue but now it shows me that ImportError: No module named joblib
Please How to resolve it?

**Comment by Jigar6591** [comment]
I am getting the same error. can you please tell me the solution for the same, as I am unable to see the solution above. Thank you

**Comment by JyothsnaVarrier** [comment]
Did anyone find the solution to this error?

**Comment by rohitnaik246** [comment]
Being tracked [in this issue](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/issues/12)
