### ISSUE TITLE
Showing every website safe for my own random_forest.pkl

### ISSUE THREAD

**Issue by NishaatK** [rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning#9]
Hi @rohitnaik246, I have created my own random_forest.pkl using train.py without any changes but still I am getting every website as safe. Why? How to get the output as Phishing for Phishing website? What changes I must do in the project? Please suggest the ideas.

**Comment by rohitnaik246** [comment]
If you created random_forest.pkl using the exact same train.py file, how is it anything new from what is already there in the model?
In this case, my suggestion would be what I discussed in [this issue](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/issues/5)
Thanks!

Closing the issue as the solution is clear. If anything is unclear, please feel free to reopen the issue.
